export { default as App } from './App/App'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Info } from './Info/Info'
export { default as Task } from './Task/Task'
export { default as Team } from './Team/Team'
export { default as Document } from './Document/Document'
export { default as Profile } from './Profile/Profile'
export { default as Page404 } from './Page404/Page404'
